//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="seatLockKey", Namespace="http://schemas.datacontract.org/2004/07/VlastelinServer")]
    [System.SerializableAttribute()]
    public partial struct seatLockKey : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long seatNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ssIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long tpIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dt {
            get {
                return this.dtField;
            }
            set {
                if ((this.dtField.Equals(value) != true)) {
                    this.dtField = value;
                    this.RaisePropertyChanged("dt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long seatNum {
            get {
                return this.seatNumField;
            }
            set {
                if ((this.seatNumField.Equals(value) != true)) {
                    this.seatNumField = value;
                    this.RaisePropertyChanged("seatNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ssId {
            get {
                return this.ssIdField;
            }
            set {
                if ((this.ssIdField.Equals(value) != true)) {
                    this.ssIdField = value;
                    this.RaisePropertyChanged("ssId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long tpId {
            get {
                return this.tpIdField;
            }
            set {
                if ((this.tpIdField.Equals(value) != true)) {
                    this.tpIdField = value;
                    this.RaisePropertyChanged("tpId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="vlastelinService", ConfigurationName="ServiceReference1.IVlastelinSrv")]
    public interface IVlastelinSrv {
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/MainSettingsGet", ReplyAction="vlastelinService/IVlastelinSrv/MainSettingsGetResponse")]
        Vlastelin.Data.Model.MainSettings MainSettingsGet();
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/MainSettingsEdit", ReplyAction="vlastelinService/IVlastelinSrv/MainSettingsEditResponse")]
        void MainSettingsEdit(Vlastelin.Data.Model.MainSettings settings);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/StationOrderGet", ReplyAction="vlastelinService/IVlastelinSrv/StationOrderGetResponse")]
        Vlastelin.Data.Model.StationOrder[] StationOrderGet(Vlastelin.Data.Model.Trip trip);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/StationOrderEdit", ReplyAction="vlastelinService/IVlastelinSrv/StationOrderEditResponse")]
        void StationOrderEdit(Vlastelin.Data.Model.Trip trip, Vlastelin.Data.Model.Town[] towns);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/StationScheduleGet", ReplyAction="vlastelinService/IVlastelinSrv/StationScheduleGetResponse")]
        Vlastelin.Data.Model.StationSchedule[] StationScheduleGet(Vlastelin.Data.Model.TripSchedule ts);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/StationScheduleAdd", ReplyAction="vlastelinService/IVlastelinSrv/StationScheduleAddResponse")]
        long StationScheduleAdd(Vlastelin.Data.Model.StationSchedule ss);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/StationScheduleEdit", ReplyAction="vlastelinService/IVlastelinSrv/StationScheduleEditResponse")]
        void StationScheduleEdit(Vlastelin.Data.Model.StationSchedule ss);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/StationScheduleDelete", ReplyAction="vlastelinService/IVlastelinSrv/StationScheduleDeleteResponse")]
        void StationScheduleDelete(Vlastelin.Data.Model.StationSchedule ss);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/StationScheduleSave", ReplyAction="vlastelinService/IVlastelinSrv/StationScheduleSaveResponse")]
        void StationScheduleSave(Vlastelin.Data.Model.StationSchedule[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/TripPricesGet", ReplyAction="vlastelinService/IVlastelinSrv/TripPricesGetResponse")]
        Vlastelin.Data.Model.TripPrice[] TripPricesGet(Vlastelin.Data.Model.Trip trip);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/TripPriceEdit", ReplyAction="vlastelinService/IVlastelinSrv/TripPriceEditResponse")]
        void TripPriceEdit(Vlastelin.Data.Model.TripPrice tp);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/TripPriceSave", ReplyAction="vlastelinService/IVlastelinSrv/TripPriceSaveResponse")]
        void TripPriceSave(Vlastelin.Data.Model.TripPrice[] tPrices);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/PKOGet", ReplyAction="vlastelinService/IVlastelinSrv/PKOGetResponse")]
        Vlastelin.Data.Model.PKO[] PKOGet(System.Nullable<long> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/PKOAdd", ReplyAction="vlastelinService/IVlastelinSrv/PKOAddResponse")]
        long PKOAdd(Vlastelin.Data.Model.PKO pko);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/SalesKindsGet", ReplyAction="vlastelinService/IVlastelinSrv/SalesKindsGetResponse")]
        Vlastelin.Data.Model.SalesKind[] SalesKindsGet(System.Nullable<long> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/SalesKindSell", ReplyAction="vlastelinService/IVlastelinSrv/SalesKindSellResponse")]
        void SalesKindSell(Vlastelin.Data.Model.Operator op, Vlastelin.Data.Model.SalesKind item, double sum, int checkNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/SalesHistoryGet", ReplyAction="vlastelinService/IVlastelinSrv/SalesHistoryGetResponse")]
        Vlastelin.Data.Model.SalesHistory[] SalesHistoryGet(System.Nullable<System.DateTime> from, System.Nullable<System.DateTime> to);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/SalesHistoryBySeat", ReplyAction="vlastelinService/IVlastelinSrv/SalesHistoryBySeatResponse")]
        Vlastelin.Data.Model.SalesHistory[] SalesHistoryBySeat(Vlastelin.Data.Model.Seat seat);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/ReportGet", ReplyAction="vlastelinService/IVlastelinSrv/ReportGetResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vlastelin.Data.Model.Town))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vlastelin.Data.Model.StationOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vlastelin.Data.Model.TripSchedule))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vlastelin.Data.Model.Bus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vlastelin.Data.Model.Owner))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vlastelin.Data.Model.NamedItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vlastelin.Data.Model.SalesKind))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vlastelin.Data.Model.DirPosition))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vlastelin.Data.Model.DriverAuthority))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vlastelin.Data.Model.FIOItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vlastelin.Data.Model.Operator))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vlastelin.Data.Model.Branch))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vlastelin.Data.Model.Passenger))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vlastelin.Data.Model.Driver))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vlastelin.Data.Model.StationSchedule))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vlastelin.Data.Model.TripPrice))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vlastelin.Data.Model.PKO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vlastelin.Data.Model.SalesHistory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vlastelin.Data.Model.Seat))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vlastelin.Data.Model.RKO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vlastelin.Data.Model.TripScheduleFact))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vlastelin.Data.Model.Trip))]
        System.Data.DataTable ReportGet(Vlastelin.Common.ReportTypes reportType, System.DateTime from, System.DateTime to, Vlastelin.Data.Model.BaseItem param1, Vlastelin.Data.Model.BaseItem param2);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/ReportStatement", ReplyAction="vlastelinService/IVlastelinSrv/ReportStatementResponse")]
        System.Data.DataTable ReportStatement(Vlastelin.Data.Model.StationSchedule ss, System.DateTime depTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/ReportPassengers", ReplyAction="vlastelinService/IVlastelinSrv/ReportPassengersResponse")]
        System.Data.DataTable ReportPassengers(System.Nullable<System.DateTime> from, System.Nullable<System.DateTime> to, string surname, string name, string patronymic);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/ExportRKO", ReplyAction="vlastelinService/IVlastelinSrv/ExportRKOResponse")]
        Vlastelin.Data.Model.ExportedData.ExportedRKO[] ExportRKO(System.Nullable<System.DateTime> from, System.Nullable<System.DateTime> to);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/GetAvailableBuses", ReplyAction="vlastelinService/IVlastelinSrv/GetAvailableBusesResponse")]
        Vlastelin.Data.Model.Bus[] GetAvailableBuses(Vlastelin.Data.Model.StationSchedule ss, System.DateTime tripDate, int minSeatsCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/OperatorChangeBus", ReplyAction="vlastelinService/IVlastelinSrv/OperatorChangeBusResponse")]
        void OperatorChangeBus(Vlastelin.Data.Model.TripSchedule ts, Vlastelin.Data.Model.Bus newBus, System.DateTime tripDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/DriverEdit", ReplyAction="vlastelinService/IVlastelinSrv/DriverEditResponse")]
        void DriverEdit(Vlastelin.Data.Model.Driver driver);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/DriversGetByBus", ReplyAction="vlastelinService/IVlastelinSrv/DriversGetByBusResponse")]
        Vlastelin.Data.Model.Driver[] DriversGetByBus(Vlastelin.Data.Model.Bus bus);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/SeatsGet", ReplyAction="vlastelinService/IVlastelinSrv/SeatsGetResponse")]
        System.Tuple<Vlastelin.Data.Model.Seat, double, string>[] SeatsGet(Vlastelin.Data.Model.StationSchedule ss, Vlastelin.Data.Model.TripPrice price, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/SeatLock", ReplyAction="vlastelinService/IVlastelinSrv/SeatLockResponse")]
        System.Tuple<System.TimeSpan, long> SeatLock(int seatNum, int ssID, int tripPriceId, System.DateTime tripDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/SeatUnlock", ReplyAction="vlastelinService/IVlastelinSrv/SeatUnlockResponse")]
        void SeatUnlock(testClient.ServiceReference1.seatLockKey slk);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/SeatSell", ReplyAction="vlastelinService/IVlastelinSrv/SeatSellResponse")]
        void SeatSell(Vlastelin.Data.Model.Operator op, Vlastelin.Data.Model.Seat seat, Vlastelin.Data.Model.Passenger passenger, double sum, int checkNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/SeatSellReturn", ReplyAction="vlastelinService/IVlastelinSrv/SeatSellReturnResponse")]
        void SeatSellReturn(Vlastelin.Data.Model.Operator op, Vlastelin.Data.Model.Seat seat, int returnCheckNumber, int commissionCheckNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/SeatReserve", ReplyAction="vlastelinService/IVlastelinSrv/SeatReserveResponse")]
        long SeatReserve(Vlastelin.Data.Model.Seat seat);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/SeatReserveCancel", ReplyAction="vlastelinService/IVlastelinSrv/SeatReserveCancelResponse")]
        void SeatReserveCancel(Vlastelin.Data.Model.Seat seat);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/PassengersGet", ReplyAction="vlastelinService/IVlastelinSrv/PassengersGetResponse")]
        Vlastelin.Data.Model.Passenger[] PassengersGet(System.Nullable<long> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/PassengerAdd", ReplyAction="vlastelinService/IVlastelinSrv/PassengerAddResponse")]
        long PassengerAdd(Vlastelin.Data.Model.Passenger passenger);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/DriverAuthorityAdd", ReplyAction="vlastelinService/IVlastelinSrv/DriverAuthorityAddResponse")]
        long DriverAuthorityAdd(int driverId, int ownerId, string num, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/DriverAuthorityDelete", ReplyAction="vlastelinService/IVlastelinSrv/DriverAuthorityDeleteResponse")]
        void DriverAuthorityDelete(int daId);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/RKOGet", ReplyAction="vlastelinService/IVlastelinSrv/RKOGetResponse")]
        Vlastelin.Data.Model.RKO[] RKOGet(System.Nullable<long> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/RKOAdd", ReplyAction="vlastelinService/IVlastelinSrv/RKOAddResponse")]
        long RKOAdd(Vlastelin.Data.Model.RKO rko);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/OperatorsGet", ReplyAction="vlastelinService/IVlastelinSrv/OperatorsGetResponse")]
        Vlastelin.Data.Model.Operator[] OperatorsGet(System.Nullable<long> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/OperatorAdd", ReplyAction="vlastelinService/IVlastelinSrv/OperatorAddResponse")]
        long OperatorAdd(Vlastelin.Data.Model.Operator op, string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/OperatorDelete", ReplyAction="vlastelinService/IVlastelinSrv/OperatorDeleteResponse")]
        void OperatorDelete(Vlastelin.Data.Model.Operator op);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/OperatorEdit", ReplyAction="vlastelinService/IVlastelinSrv/OperatorEditResponse")]
        void OperatorEdit(Vlastelin.Data.Model.Operator op, string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/OperatorGetByLogin", ReplyAction="vlastelinService/IVlastelinSrv/OperatorGetByLoginResponse")]
        Vlastelin.Data.Model.Operator OperatorGetByLogin(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/BranchesGet", ReplyAction="vlastelinService/IVlastelinSrv/BranchesGetResponse")]
        Vlastelin.Data.Model.Branch[] BranchesGet(System.Nullable<long> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/BranchAdd", ReplyAction="vlastelinService/IVlastelinSrv/BranchAddResponse")]
        long BranchAdd(Vlastelin.Data.Model.Branch branch);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/BranchDelete", ReplyAction="vlastelinService/IVlastelinSrv/BranchDeleteResponse")]
        void BranchDelete(Vlastelin.Data.Model.Branch branch);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/BranchEdit", ReplyAction="vlastelinService/IVlastelinSrv/BranchEditResponse")]
        void BranchEdit(Vlastelin.Data.Model.Branch branch);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/TripScheduleFactGet", ReplyAction="vlastelinService/IVlastelinSrv/TripScheduleFactGetResponse")]
        Vlastelin.Data.Model.TripScheduleFact[] TripScheduleFactGet(System.Nullable<long> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/TripScheduleFactGetByDate", ReplyAction="vlastelinService/IVlastelinSrv/TripScheduleFactGetByDateResponse")]
        Vlastelin.Data.Model.TripScheduleFact[] TripScheduleFactGetByDate(System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/TripScheduleFactAdd", ReplyAction="vlastelinService/IVlastelinSrv/TripScheduleFactAddResponse")]
        long TripScheduleFactAdd(Vlastelin.Data.Model.TripScheduleFact tsf);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/TripScheduleFactDelete", ReplyAction="vlastelinService/IVlastelinSrv/TripScheduleFactDeleteResponse")]
        void TripScheduleFactDelete(Vlastelin.Data.Model.TripScheduleFact tsf);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/GetData", ReplyAction="vlastelinService/IVlastelinSrv/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/TestConnection", ReplyAction="vlastelinService/IVlastelinSrv/TestConnectionResponse")]
        int TestConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/GetLastModifiedTime", ReplyAction="vlastelinService/IVlastelinSrv/GetLastModifiedTimeResponse")]
        System.DateTime GetLastModifiedTime(Vlastelin.Common.ModifiedObjects obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/TownsGet", ReplyAction="vlastelinService/IVlastelinSrv/TownsGetResponse")]
        Vlastelin.Data.Model.Town[] TownsGet(System.Nullable<long> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/TownAdd", ReplyAction="vlastelinService/IVlastelinSrv/TownAddResponse")]
        long TownAdd(Vlastelin.Data.Model.Town town);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/TownDelete", ReplyAction="vlastelinService/IVlastelinSrv/TownDeleteResponse")]
        void TownDelete(Vlastelin.Data.Model.Town town);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/TownEdit", ReplyAction="vlastelinService/IVlastelinSrv/TownEditResponse")]
        void TownEdit(Vlastelin.Data.Model.Town town);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/DocNumGetNextNumber", ReplyAction="vlastelinService/IVlastelinSrv/DocNumGetNextNumberResponse")]
        string DocNumGetNextNumber(Vlastelin.Data.Model.Town t);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/OwnersGet", ReplyAction="vlastelinService/IVlastelinSrv/OwnersGetResponse")]
        Vlastelin.Data.Model.Owner[] OwnersGet(System.Nullable<long> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/OwnerAdd", ReplyAction="vlastelinService/IVlastelinSrv/OwnerAddResponse")]
        long OwnerAdd(Vlastelin.Data.Model.Owner owner);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/OwnerDelete", ReplyAction="vlastelinService/IVlastelinSrv/OwnerDeleteResponse")]
        void OwnerDelete(Vlastelin.Data.Model.Owner owner);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/OwnerEdit", ReplyAction="vlastelinService/IVlastelinSrv/OwnerEditResponse")]
        void OwnerEdit(Vlastelin.Data.Model.Owner owner);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/BusesGet", ReplyAction="vlastelinService/IVlastelinSrv/BusesGetResponse")]
        Vlastelin.Data.Model.Bus[] BusesGet(System.Nullable<long> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/BusAdd", ReplyAction="vlastelinService/IVlastelinSrv/BusAddResponse")]
        long BusAdd(Vlastelin.Data.Model.Bus bus);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/BusDelete", ReplyAction="vlastelinService/IVlastelinSrv/BusDeleteResponse")]
        void BusDelete(Vlastelin.Data.Model.Bus bus);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/BusEdit", ReplyAction="vlastelinService/IVlastelinSrv/BusEditResponse")]
        void BusEdit(Vlastelin.Data.Model.Bus bus);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/TripsGet", ReplyAction="vlastelinService/IVlastelinSrv/TripsGetResponse")]
        Vlastelin.Data.Model.Trip[] TripsGet(System.Nullable<long> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/TripAdd", ReplyAction="vlastelinService/IVlastelinSrv/TripAddResponse")]
        long TripAdd(Vlastelin.Data.Model.Trip trip);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/TripDelete", ReplyAction="vlastelinService/IVlastelinSrv/TripDeleteResponse")]
        void TripDelete(Vlastelin.Data.Model.Trip trip);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/TripEdit", ReplyAction="vlastelinService/IVlastelinSrv/TripEditResponse")]
        void TripEdit(Vlastelin.Data.Model.Trip trip);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/TripScheduleGet", ReplyAction="vlastelinService/IVlastelinSrv/TripScheduleGetResponse")]
        Vlastelin.Data.Model.TripSchedule[] TripScheduleGet(System.Nullable<long> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/TripScheduleAdd", ReplyAction="vlastelinService/IVlastelinSrv/TripScheduleAddResponse")]
        long TripScheduleAdd(Vlastelin.Data.Model.TripSchedule ts);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/TripScheduleDelete", ReplyAction="vlastelinService/IVlastelinSrv/TripScheduleDeleteResponse")]
        void TripScheduleDelete(Vlastelin.Data.Model.TripSchedule ts);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/TripScheduleEdit", ReplyAction="vlastelinService/IVlastelinSrv/TripScheduleEditResponse")]
        void TripScheduleEdit(Vlastelin.Data.Model.TripSchedule ts);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/TripScheduleSave", ReplyAction="vlastelinService/IVlastelinSrv/TripScheduleSaveResponse")]
        void TripScheduleSave(Vlastelin.Data.Model.TripSchedule ts, Vlastelin.Data.Model.StationSchedule[] ss);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/DriversGet", ReplyAction="vlastelinService/IVlastelinSrv/DriversGetResponse")]
        Vlastelin.Data.Model.Driver[] DriversGet(System.Nullable<long> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/DriverAdd", ReplyAction="vlastelinService/IVlastelinSrv/DriverAddResponse")]
        long DriverAdd(Vlastelin.Data.Model.Driver driver);
        
        [System.ServiceModel.OperationContractAttribute(Action="vlastelinService/IVlastelinSrv/DriverDelete", ReplyAction="vlastelinService/IVlastelinSrv/DriverDeleteResponse")]
        void DriverDelete(Vlastelin.Data.Model.Driver driver);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVlastelinSrvChannel : testClient.ServiceReference1.IVlastelinSrv, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VlastelinSrvClient : System.ServiceModel.ClientBase<testClient.ServiceReference1.IVlastelinSrv>, testClient.ServiceReference1.IVlastelinSrv {
        
        public VlastelinSrvClient() {
        }
        
        public VlastelinSrvClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VlastelinSrvClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VlastelinSrvClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VlastelinSrvClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Vlastelin.Data.Model.MainSettings MainSettingsGet() {
            return base.Channel.MainSettingsGet();
        }
        
        public void MainSettingsEdit(Vlastelin.Data.Model.MainSettings settings) {
            base.Channel.MainSettingsEdit(settings);
        }
        
        public Vlastelin.Data.Model.StationOrder[] StationOrderGet(Vlastelin.Data.Model.Trip trip) {
            return base.Channel.StationOrderGet(trip);
        }
        
        public void StationOrderEdit(Vlastelin.Data.Model.Trip trip, Vlastelin.Data.Model.Town[] towns) {
            base.Channel.StationOrderEdit(trip, towns);
        }
        
        public Vlastelin.Data.Model.StationSchedule[] StationScheduleGet(Vlastelin.Data.Model.TripSchedule ts) {
            return base.Channel.StationScheduleGet(ts);
        }
        
        public long StationScheduleAdd(Vlastelin.Data.Model.StationSchedule ss) {
            return base.Channel.StationScheduleAdd(ss);
        }
        
        public void StationScheduleEdit(Vlastelin.Data.Model.StationSchedule ss) {
            base.Channel.StationScheduleEdit(ss);
        }
        
        public void StationScheduleDelete(Vlastelin.Data.Model.StationSchedule ss) {
            base.Channel.StationScheduleDelete(ss);
        }
        
        public void StationScheduleSave(Vlastelin.Data.Model.StationSchedule[] list) {
            base.Channel.StationScheduleSave(list);
        }
        
        public Vlastelin.Data.Model.TripPrice[] TripPricesGet(Vlastelin.Data.Model.Trip trip) {
            return base.Channel.TripPricesGet(trip);
        }
        
        public void TripPriceEdit(Vlastelin.Data.Model.TripPrice tp) {
            base.Channel.TripPriceEdit(tp);
        }
        
        public void TripPriceSave(Vlastelin.Data.Model.TripPrice[] tPrices) {
            base.Channel.TripPriceSave(tPrices);
        }
        
        public Vlastelin.Data.Model.PKO[] PKOGet(System.Nullable<long> id) {
            return base.Channel.PKOGet(id);
        }
        
        public long PKOAdd(Vlastelin.Data.Model.PKO pko) {
            return base.Channel.PKOAdd(pko);
        }
        
        public Vlastelin.Data.Model.SalesKind[] SalesKindsGet(System.Nullable<long> id) {
            return base.Channel.SalesKindsGet(id);
        }
        
        public void SalesKindSell(Vlastelin.Data.Model.Operator op, Vlastelin.Data.Model.SalesKind item, double sum, int checkNumber) {
            base.Channel.SalesKindSell(op, item, sum, checkNumber);
        }
        
        public Vlastelin.Data.Model.SalesHistory[] SalesHistoryGet(System.Nullable<System.DateTime> from, System.Nullable<System.DateTime> to) {
            return base.Channel.SalesHistoryGet(from, to);
        }
        
        public Vlastelin.Data.Model.SalesHistory[] SalesHistoryBySeat(Vlastelin.Data.Model.Seat seat) {
            return base.Channel.SalesHistoryBySeat(seat);
        }
        
        public System.Data.DataTable ReportGet(Vlastelin.Common.ReportTypes reportType, System.DateTime from, System.DateTime to, Vlastelin.Data.Model.BaseItem param1, Vlastelin.Data.Model.BaseItem param2) {
            return base.Channel.ReportGet(reportType, from, to, param1, param2);
        }
        
        public System.Data.DataTable ReportStatement(Vlastelin.Data.Model.StationSchedule ss, System.DateTime depTime) {
            return base.Channel.ReportStatement(ss, depTime);
        }
        
        public System.Data.DataTable ReportPassengers(System.Nullable<System.DateTime> from, System.Nullable<System.DateTime> to, string surname, string name, string patronymic) {
            return base.Channel.ReportPassengers(from, to, surname, name, patronymic);
        }
        
        public Vlastelin.Data.Model.ExportedData.ExportedRKO[] ExportRKO(System.Nullable<System.DateTime> from, System.Nullable<System.DateTime> to) {
            return base.Channel.ExportRKO(from, to);
        }
        
        public Vlastelin.Data.Model.Bus[] GetAvailableBuses(Vlastelin.Data.Model.StationSchedule ss, System.DateTime tripDate, int minSeatsCount) {
            return base.Channel.GetAvailableBuses(ss, tripDate, minSeatsCount);
        }
        
        public void OperatorChangeBus(Vlastelin.Data.Model.TripSchedule ts, Vlastelin.Data.Model.Bus newBus, System.DateTime tripDate) {
            base.Channel.OperatorChangeBus(ts, newBus, tripDate);
        }
        
        public void DriverEdit(Vlastelin.Data.Model.Driver driver) {
            base.Channel.DriverEdit(driver);
        }
        
        public Vlastelin.Data.Model.Driver[] DriversGetByBus(Vlastelin.Data.Model.Bus bus) {
            return base.Channel.DriversGetByBus(bus);
        }
        
        public System.Tuple<Vlastelin.Data.Model.Seat, double, string>[] SeatsGet(Vlastelin.Data.Model.StationSchedule ss, Vlastelin.Data.Model.TripPrice price, System.DateTime date) {
            return base.Channel.SeatsGet(ss, price, date);
        }
        
        public System.Tuple<System.TimeSpan, long> SeatLock(int seatNum, int ssID, int tripPriceId, System.DateTime tripDate) {
            return base.Channel.SeatLock(seatNum, ssID, tripPriceId, tripDate);
        }
        
        public void SeatUnlock(testClient.ServiceReference1.seatLockKey slk) {
            base.Channel.SeatUnlock(slk);
        }
        
        public void SeatSell(Vlastelin.Data.Model.Operator op, Vlastelin.Data.Model.Seat seat, Vlastelin.Data.Model.Passenger passenger, double sum, int checkNum) {
            base.Channel.SeatSell(op, seat, passenger, sum, checkNum);
        }
        
        public void SeatSellReturn(Vlastelin.Data.Model.Operator op, Vlastelin.Data.Model.Seat seat, int returnCheckNumber, int commissionCheckNumber) {
            base.Channel.SeatSellReturn(op, seat, returnCheckNumber, commissionCheckNumber);
        }
        
        public long SeatReserve(Vlastelin.Data.Model.Seat seat) {
            return base.Channel.SeatReserve(seat);
        }
        
        public void SeatReserveCancel(Vlastelin.Data.Model.Seat seat) {
            base.Channel.SeatReserveCancel(seat);
        }
        
        public Vlastelin.Data.Model.Passenger[] PassengersGet(System.Nullable<long> id) {
            return base.Channel.PassengersGet(id);
        }
        
        public long PassengerAdd(Vlastelin.Data.Model.Passenger passenger) {
            return base.Channel.PassengerAdd(passenger);
        }
        
        public long DriverAuthorityAdd(int driverId, int ownerId, string num, System.DateTime date) {
            return base.Channel.DriverAuthorityAdd(driverId, ownerId, num, date);
        }
        
        public void DriverAuthorityDelete(int daId) {
            base.Channel.DriverAuthorityDelete(daId);
        }
        
        public Vlastelin.Data.Model.RKO[] RKOGet(System.Nullable<long> id) {
            return base.Channel.RKOGet(id);
        }
        
        public long RKOAdd(Vlastelin.Data.Model.RKO rko) {
            return base.Channel.RKOAdd(rko);
        }
        
        public Vlastelin.Data.Model.Operator[] OperatorsGet(System.Nullable<long> id) {
            return base.Channel.OperatorsGet(id);
        }
        
        public long OperatorAdd(Vlastelin.Data.Model.Operator op, string login, string password) {
            return base.Channel.OperatorAdd(op, login, password);
        }
        
        public void OperatorDelete(Vlastelin.Data.Model.Operator op) {
            base.Channel.OperatorDelete(op);
        }
        
        public void OperatorEdit(Vlastelin.Data.Model.Operator op, string login, string password) {
            base.Channel.OperatorEdit(op, login, password);
        }
        
        public Vlastelin.Data.Model.Operator OperatorGetByLogin(string login) {
            return base.Channel.OperatorGetByLogin(login);
        }
        
        public Vlastelin.Data.Model.Branch[] BranchesGet(System.Nullable<long> id) {
            return base.Channel.BranchesGet(id);
        }
        
        public long BranchAdd(Vlastelin.Data.Model.Branch branch) {
            return base.Channel.BranchAdd(branch);
        }
        
        public void BranchDelete(Vlastelin.Data.Model.Branch branch) {
            base.Channel.BranchDelete(branch);
        }
        
        public void BranchEdit(Vlastelin.Data.Model.Branch branch) {
            base.Channel.BranchEdit(branch);
        }
        
        public Vlastelin.Data.Model.TripScheduleFact[] TripScheduleFactGet(System.Nullable<long> id) {
            return base.Channel.TripScheduleFactGet(id);
        }
        
        public Vlastelin.Data.Model.TripScheduleFact[] TripScheduleFactGetByDate(System.DateTime dt) {
            return base.Channel.TripScheduleFactGetByDate(dt);
        }
        
        public long TripScheduleFactAdd(Vlastelin.Data.Model.TripScheduleFact tsf) {
            return base.Channel.TripScheduleFactAdd(tsf);
        }
        
        public void TripScheduleFactDelete(Vlastelin.Data.Model.TripScheduleFact tsf) {
            base.Channel.TripScheduleFactDelete(tsf);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public int TestConnection() {
            return base.Channel.TestConnection();
        }
        
        public System.DateTime GetLastModifiedTime(Vlastelin.Common.ModifiedObjects obj) {
            return base.Channel.GetLastModifiedTime(obj);
        }
        
        public Vlastelin.Data.Model.Town[] TownsGet(System.Nullable<long> id) {
            return base.Channel.TownsGet(id);
        }
        
        public long TownAdd(Vlastelin.Data.Model.Town town) {
            return base.Channel.TownAdd(town);
        }
        
        public void TownDelete(Vlastelin.Data.Model.Town town) {
            base.Channel.TownDelete(town);
        }
        
        public void TownEdit(Vlastelin.Data.Model.Town town) {
            base.Channel.TownEdit(town);
        }
        
        public string DocNumGetNextNumber(Vlastelin.Data.Model.Town t) {
            return base.Channel.DocNumGetNextNumber(t);
        }
        
        public Vlastelin.Data.Model.Owner[] OwnersGet(System.Nullable<long> id) {
            return base.Channel.OwnersGet(id);
        }
        
        public long OwnerAdd(Vlastelin.Data.Model.Owner owner) {
            return base.Channel.OwnerAdd(owner);
        }
        
        public void OwnerDelete(Vlastelin.Data.Model.Owner owner) {
            base.Channel.OwnerDelete(owner);
        }
        
        public void OwnerEdit(Vlastelin.Data.Model.Owner owner) {
            base.Channel.OwnerEdit(owner);
        }
        
        public Vlastelin.Data.Model.Bus[] BusesGet(System.Nullable<long> id) {
            return base.Channel.BusesGet(id);
        }
        
        public long BusAdd(Vlastelin.Data.Model.Bus bus) {
            return base.Channel.BusAdd(bus);
        }
        
        public void BusDelete(Vlastelin.Data.Model.Bus bus) {
            base.Channel.BusDelete(bus);
        }
        
        public void BusEdit(Vlastelin.Data.Model.Bus bus) {
            base.Channel.BusEdit(bus);
        }
        
        public Vlastelin.Data.Model.Trip[] TripsGet(System.Nullable<long> id) {
            return base.Channel.TripsGet(id);
        }
        
        public long TripAdd(Vlastelin.Data.Model.Trip trip) {
            return base.Channel.TripAdd(trip);
        }
        
        public void TripDelete(Vlastelin.Data.Model.Trip trip) {
            base.Channel.TripDelete(trip);
        }
        
        public void TripEdit(Vlastelin.Data.Model.Trip trip) {
            base.Channel.TripEdit(trip);
        }
        
        public Vlastelin.Data.Model.TripSchedule[] TripScheduleGet(System.Nullable<long> id) {
            return base.Channel.TripScheduleGet(id);
        }
        
        public long TripScheduleAdd(Vlastelin.Data.Model.TripSchedule ts) {
            return base.Channel.TripScheduleAdd(ts);
        }
        
        public void TripScheduleDelete(Vlastelin.Data.Model.TripSchedule ts) {
            base.Channel.TripScheduleDelete(ts);
        }
        
        public void TripScheduleEdit(Vlastelin.Data.Model.TripSchedule ts) {
            base.Channel.TripScheduleEdit(ts);
        }
        
        public void TripScheduleSave(Vlastelin.Data.Model.TripSchedule ts, Vlastelin.Data.Model.StationSchedule[] ss) {
            base.Channel.TripScheduleSave(ts, ss);
        }
        
        public Vlastelin.Data.Model.Driver[] DriversGet(System.Nullable<long> id) {
            return base.Channel.DriversGet(id);
        }
        
        public long DriverAdd(Vlastelin.Data.Model.Driver driver) {
            return base.Channel.DriverAdd(driver);
        }
        
        public void DriverDelete(Vlastelin.Data.Model.Driver driver) {
            base.Channel.DriverDelete(driver);
        }
    }
}
